name: CI Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências
      run: npm ci
      working-directory: promodb_front

    - name: Build do SvelteKit
      run: npm run build
      working-directory: promodb_front

    - name: Testar leitura do secret DOCKERHUB_USERNAME
      run: echo "Usuário do DockerHub tem ${#DOCKERHUB_USERNAME} caracteres"
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Login no DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Definir TAG com data e hora
      id: datetime
      run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

    - name: Construir e enviar imagem para DockerHub
      uses: docker/build-push-action@v5
      with:
        context: ./promodb_frontend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/promodb_frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/promodb_front:${{ env.TAG }}