name: workflow.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build-and-test:
    runs-on: ubuntu-latestu

    steps:
      - name: Clone do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar o Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configura cache do Poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}


      - name: Instalar os pacotes e dependedências
        run: | 
          poetry install
